@url=http://10.255.200.18:8080

POST {{url}}/data
content-type: application/json

{
    "svc_type": "svc1",
    "src_ton": 0,
    "src_npi": 0,
    "src_addr": "123",
    "dst_ton": 0,
    "dst_npi": 0,
    "dst_addr": "987",
    "esm_class": 0,
    "registered_delivery": 0,
    "data_coding": 0,
    "options": {
        "1060": "dGVzdGRhdGE="
    }
}

###
POST {{url}}/deliver
content-type: application/json

{
    "svc_type": "svc1",
    "src_ton": 0,
    "src_npi": 0,
    "src_addr": "123",
    "dst_ton": 0,
    "dst_npi": 0,
    "dst_addr": "987",
    "esm_class": 0,
    "protocol_id": 0,
    "priority_flag": 0,
    "schedule_delivery_time": "",
    "validity_period": "",
    "registered_delivery": 0,
    "replace_if_present_flag": 0,
    "data_coding": 0,
    "sm_default_sm_id": 0,
    "short_message": "",
    "options": {}
}